import type { ProviderTemplate } from './types';

export const PROVIDER_TEMPLATES: ProviderTemplate[] = [
  {
    id:       'theHarvester',
    name:     'theHarvester',
    desc:     'CLI tool for gathering emails, subdomains, hosts, and employee names from public sources.',
    category: 'domain',
    exec:     'subprocess',
    seeds:    ['domain', 'org'],
    endpoint: 'theHarvester',
  },
  {
    id:       'shodan',
    name:     'Shodan',
    desc:     'Internet-wide scanner. Search for devices, open ports, banners, and CVEs by IP or domain.',
    category: 'network',
    exec:     'api',
    seeds:    ['ip', 'domain'],
    endpoint: 'https://api.shodan.io',
  },
  {
    id:       'whois',
    name:     'WHOIS',
    desc:     'Domain registration data — registrant, registrar, nameservers, and expiry dates.',
    category: 'domain',
    exec:     'api',
    seeds:    ['domain'],
    endpoint: 'https://who-dat.as93.net',
  },
  {
    id:       'crtsh',
    name:     'crt.sh',
    desc:     'Certificate Transparency log search. Enumerate subdomains via SSL/TLS certificate records.',
    category: 'domain',
    exec:     'api',
    seeds:    ['domain'],
    endpoint: 'https://crt.sh',
  },
  {
    id:       'hibp',
    name:     'HaveIBeenPwned',
    desc:     'Check an email address against known data breach databases.',
    category: 'email',
    exec:     'api',
    seeds:    ['email'],
    endpoint: 'https://haveibeenpwned.com/api/v3',
  },
  {
    id:       'virustotal',
    name:     'VirusTotal',
    desc:     'Multi-engine analysis for IPs, domains, file hashes, and URLs. Surfaces reputation and related IOCs.',
    category: 'network',
    exec:     'api',
    seeds:    ['ip', 'domain', 'hash', 'url'],
    endpoint: 'https://www.virustotal.com/api/v3',
  },
  {
    id:       'spiderfoot',
    name:     'SpiderFoot',
    desc:     'Self-hosted OSINT automation framework. Aggregates 200+ modules for comprehensive target profiling.',
    category: 'domain',
    exec:     'api',
    seeds:    ['domain', 'ip', 'email', 'username'],
    endpoint: 'http://localhost:5001',
  },
  {
    id:       'custom',
    name:     'Custom',
    desc:     'Define your own provider — any API, CLI tool, or local script.',
    category: 'custom',
    exec:     'api',
    seeds:    [],
    endpoint: '',
  },
];
